//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmdt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tintuc
    {
        public int ma { get; set; }
        public string tieude { get; set; }
        public int macm { get; set; }
        public string matangan { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public string anh { get; set; }
        public string nguoidang { get; set; }
        public Nullable<bool> tieubieu { get; set; }
        public string loaitin { get; set; }
    
        public virtual chuyenmuc chuyenmuc { get; set; }
    }
}
