//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmdt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoidung
    {
        public int ma { get; set; }
        public string ten { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string email { get; set; }
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public string anh { get; set; }
        public string quyen { get; set; }
    }
}
